# fly.toml app configuration file generated for slworks-invoicer on 2026-07-21T20:56:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slworks-invoicer'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'garage_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
